name: Pinpoint Site Deployment

on:
   push:
      branches: [master]

jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
         - uses: actions/checkout@v2
         - uses: actions/cache@v2
           with:
              path: ${{ github.workspace }}/.next/cache
              # Generate a new cache whenever packages or source files change.
              key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
              # If source files changed but packages didn't, rebuild from a prior cache.
              restore-keys: |
                 ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v1
           with:
              node-version: 14
         - run: npm install
         - run: npm run build
         - name: Deploy Site
           run: npm run deploy
           if: env.PINPOINT_API_KEY != null
           env:
              PINPOINT_API_KEY: ${{ secrets.PINPOINT_API_KEY }}
